In [ ]:
import torch

# torch machine learning 형태
x,y=get_data() # x는 훈련데이터, y는 목표변수
w,b=get_weights() # w 는 가중치 b는 bias
for i in range(50000): # 50000번 반복
  y_pred=simple_network(x) # wx+b=y_pred 의 simple network
  loss=loss_fn(y,y_pred) # loss function은 MSE 연산 (제곱 합 계산)
  if i% 5000==0: # 5000step마다 출력
    print(loss)
  optimize(learning_rate) # w,b파라미터 조정
####This section is not operating####

In [ ]:
import torch
'''Tensor
Scalar: 0dim tensor
Vector: 1dim Tensor
Matrix: 2dim Tensor
Image : 3dim Tensor
-> usually use 5dims in deep learning
'''

# 0dim Tensor
x=torch.tensor(10)
print("0 dim Tensor",x)
print("Dimension: ",x.dim())

# 1dim Tensor :Vector
# -> Float, Long type tensor
x=torch.rand(10) # 10개의 0부터1을 뽑음
print(x)
print("Dimension: ",x.dim())

temp = torch.FloatTensor([23,24,24.5,26,27,27,23.3]) 
print("Tensor size: ", temp.size())

# 2 dim Tenro : Matrix
z=torch.rand([20,10])
print("z tensor size:", z.size())
print(z[:2])

# 3 dim Tensor: Image
"""
3차원은 표기하기 힘드므로 예제
from PIL import Image
x= np.array(Image,open('panda.jpg').resize(224,224))
x_tensor=torch.from_numpy(x) # torch의 tensor로 np 변경
plt.imshow(x)
"""

0 dim Tensor tensor(10)
Dimension:  0
tensor([0.5907, 0.6854, 0.3301, 0.3051, 0.1083, 0.9758, 0.4530, 0.3957, 0.8323,
        0.2123])
Dimension:  1
Tensor size:  torch.Size([7])
z tensor size: torch.Size([20, 10])
tensor([[0.7937, 0.0803, 0.9679, 0.5490, 0.7160, 0.2541, 0.6349, 0.7771, 0.5299,
         0.3332],
        [0.8393, 0.7855, 0.9882, 0.8230, 0.5843, 0.1193, 0.8878, 0.0728, 0.8311,
         0.4179]])


In [ ]:
#Tensor slicing
#dict slicing 과 동일

sales = torch.eye(3,3) #대각행렬 만들고 대각요소를 1로 채움 
print(sales[1,1]) # 대각 행렬 검사

# 4차원 이상의 텐서는 이미지 연속처리에 보통 사용한다.
'''
cats=glob(data_path+'*.jpg')
cat_imgs=np.array([np.array(Image.open(cat).resize(224,224) for cat in cats[:64]])
cat_imgs
--> Tensor : 64*224*224*3 channel
64장의 이미지 동시 로딩 라고 볼 수 있음
'''

tensor(1.)

In [ ]:
#Calculation
a=torch.rand(2,2)
b=torch.rand(2,2)
c=a+b
d=torch.add(a,b)
a.add_(5)
a*b
a.mul(b)

In [ ]:

import torch

#cuda-> GPU Tensor

#cpu tensor 객체
a=torch.rand(10000,10000)
b=torch.rand(10000,10000)
a.matmul(b)

#gpu tensor 객체로의 변환
a=a.cuda()
b=b.cuda()
a.matmul(b)


In [ ]:
#Variiable 가변 계산 그래프 <- Tensor 객체, 기울기, Variable생성하는 함수의 참조로 구성
import torch
from torch.autograd import Variable
x=Variable(torch.ones(2,2),requires_grad=True)

y=x.mean()
y.backward() # 기울기 계산
print(x.grad)
print(x.grad_fn)
print(x.data)
print(y.grad_fn)

def get_data():#처음 값 받아오기
  train_X=np.asarray([3.3,4.4,5.5,6.71,6.93,4.168])
  train_Y=np.asarray([1.7,2.76,2.09,3.19,1.694,1.573])
  
  dtype=torch.FloatTensor
  X=Variable(torch.from_numpy(train_X)/type(dtype),requires_grad=False).view(17,1)
  y=Variable(torch.from_numpy(train_Y)/type(dtype),requires_grad=False)
  return X,y

def get_weights(): #가중치 및 bias를 random하게 불러오기
  w=Variable(torch.randn(1),requires_grad=True)
  b=Variable(torch.randn(1),requires_grad=True)
  return w,b

# Network 구현
def simple_network(x): #-> nn.Linear(17,1)
  y_pred=torch.matmul(x,w)+b #xW+b
  return y_pred

# 손실함수 loss function
def loss_fn(y,y_pred):
  loss=(y_pred-y).pow(2).sum() # ^2 +^2
  for param in [w,b]: # 각 가중치와 바이어스에 대해
    if not param.grad is None: # gradient 값이 존재하면 
      param.grad.data.zero_() #모두 0으로 만들어주고
  loss.backward() # backward propagation을 통해 gradient와 나머지 계산
  return loss.data[0]

def optimize(learning_rate): # optimizing 
  w.data-=learning_rate*w.grad.data
  b.data-=learning_rate*b.grad.data

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
None
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Data setting
from torch.utils.data import Dataset

class DogsAndCatsDataset(Dataset):
  def __init__(self,): #초기화
    pass
  def __len__(self): # 최대 요소수 반환
    pass
  def __getitem__(self,idx): # 데이터셋에서 idx번째 해당요소 반환
    pass

class DogsAndCatsDataset(Dataset):
  def __init__(self,root_dir,size(224,224)):
    self.files=glob(root_dir)
    self.size=size
  def __len__(self):
    return len(self.files)
  def __getitem__self(idx):
    img=np.asarray(Image.open(self.files[idx])).resize(self.size))
    label=self.files[idx].split('/')[-2]
    return img,label

# CPU에게 권장되는 인스턴스 단위 : 1
# for image,label in dogsdset:
# GPU에게 권장되는 인스턴스 단위 : Batch size

# Data loading -> DataLoader
from torch.utils.data import DataLoader
dataloader=DataLoader(dogsdset,batch_size=32,num_workers=2)
for imgs,labels in dataloader:
  pass



In [ ]:
#Activation Function <- 주로 비선형 함수
# 선형함수의 경우 2개 layer와 1개 layer와 같은 형태일 수 있으므로 사용 x
#ex) y=6(x_1)-3 == y=3(2(x_1))-3

#1.Sigmoid
# 1/(1+e^-x)
# 큰 음수=>0, 큰양수=>1
# 단점: 0이나 1에 출력이 가까워지면 시그모이드 함수의 앞 layer 기울기가 거의 0이 된다.
#  그러므로 가중치가 조정되지 않는 현상이 발생할 수 있어서 죽은뉴런이 되어버린다.

#2. tanh
# tanh(x)
# 1,-1사이의 값을 반환한다. sigmoid와 마찬가지로 -1과 1에서 기울기가 0에 가까워 죽은 뉴런이 발생한다.
# but, 출력이 0과 1중심으로 형성되므로 기울기가 소멸하는 증상이 덜 발생하여 더 많이 사용한다.

#3. ReLU
# max(0,x)
# 가장 많이 쓰임, optimizer가 더 빨리 올바른 가중치를 찾도록 돕는다.
# ReLU는 SGD(stochastic gradient descent)가 빨리 수렴하도록 한다.
# 연산 시간이 매우 짧고 단순히 0이라는 임곗값만을 가진다.
# 단점 : back propagation을 진행하면서 기울기가 큰 값을 ReLU에 전달하면 응답이 없어진다. (dead neural현상)
# learning rate를 신중하게 설정함으로써 방지할 수 있다.

#4. Leaky ReLU
# ReLU에서 0에서 수렴하여 더이상 학습하지 않는 문제를 해결하기 위해 등장.
# 음수가 입력될 경우에 0이 아닌 0.001과 같은 매우 작은수를 반환한다.
# 하지만 일관적으로 다른 activate function보다 우수한 성능을 보장하지는 않는다.
from torch.nn import ReLU
import torch
sample_data= torch.Tensor([1,2,-1,-1])
myReLU=ReLU()
myReLU(sample_data)
print(myReLU(sample_data))

tensor([1., 2., 0., 0.])


In [ ]:
# torch의 모든 network는 클래스 형태로 개발되므로 network를 구현하는 클래스는 nn.Module을 상속하고
# __init__과 forward 매서드를 구현해야한다.
# __init__은 layer 초기화
# forward 초기화한 레이어에 입력데이터 전달 후 최종출력을 반환
# super
# super는 자식클래스에서 부모클래스 인자를 사용하고 싶은경우 활용

# Model Architecture
#1. Regression 예측 모델 (연속값 출력)

#2. Binary Classification problem 분류 모델 (Discrete ->마지막 layer Sigmoid activate function)

#3. Multi-Class Classification 다중분류 모델 (Stochastic, 마지막 layer Softmax Layer)
# 확률을 반환하며, 입력데이터가 각 클래스로 분류될 확률을 반환한다. (100%는 존재할 수 없을 것임)

#구현법
import torch
import torch.nn
class MyFirstNetwork(nn.Module):
  def __init__(self,input_size,hidden_size,output_size):
    super(MyFirstNetwork,self).__init__()
    self.layer1=nn.linear(input_size,hidden_size)
    self.layer2=nn.linear(hidden_size,output_size)
  def forward(self,input):
    out=self.layer1(input)
    out=nn.ReLU(out)
    out=self.layer2(out)
    return out

In [ ]:
#오차함수 loss function
# 가중치 최적화 작업하는 함수 <- Gradient Descent 와 같은 작업을 수행함 
# 오차함수 반환 값의 최소화하는 반복적인 과정 

# Regression Model에서는 MSE(평균제곱오차)를 주로 사용
from torch.autograd import Variable
import torch
import torch.nn
loss=nn.MSELoess()
input=Variable(torch.randn(3,5),requires_grad)
target=Variable(torch.randn(3,5))
output=loss(input,target)
output.backward()

# Classification에서는 Cross-Entropy loss를 사용한다.
# Entropy는 확률을 예측하는 분류 네트워크의 오차를 계산한다. Softmax layer에서 총합은 1
# Entropy는 낮은 확률로 분류할 때 증가하며, 높은 확률로 분류할 때 감소한다.
def cross_entropy(true_label,prediction):
  if true_label==1:
    return -log(prediction)
  else:
    return -log(1-prediction)

loss=nn.CrossEntropyLoss()
input=Variable(torch.randn(3,5),requires_grad)
target=Variable(torch.randn(3,5))
output=loss(input,target)
output.backward()

# 오차함수종류
#1. L1 loss : Normalization에 사용
#2. MSE Loss : Regression Model에 주로 사용
#3. Cross Entropy loss : 이진,다중 분류 모델에 사용
#4. NLL Loss : 분류문제에서 특정 가중치를 사용해 데이터 셋 불균형을 처리할 때 사용
#5. NLL Loss2d: 이미지 분할과 관련된 문제에서 픽셀단위 분류에 사용됨

In [ ]:
#네트워크 Architecture Optimization
# 알고리즘의 정확도를 높이기 위해 가중치를 최적화한다.
# ADADELTA, Adagrad, Adam, LBFGS, SparseAdam, RMSProp, Adamax, Rprop, ASGD, SGD

#예제
optimizer=optim.SGD(model.parameters(),lr=0.01)

for input, target in dataset:
  optimizer.zero_grad()#기울기 0으로 초기화 <-안하면 기울기가 누적됨
  output=model(output)
  loss=loss_fn(output,target)
  loss.backward()#기울기 계산
  optimizer.step()#학습파라미터에 실제변경이 적용