In [ ]:
import torch

# torch machine learning 형태
x,y=get_data() # x는 훈련데이터, y는 목표변수
w,b=get_weights() # w 는 가중치 b는 bias
for i in range(50000): # 50000번 반복
  y_pred=simple_network(x) # wx+b=y_pred 의 simple network
  loss=loss_fn(y,y_pred) # loss function은 MSE 연산 (제곱 합 계산)
  if i% 5000==0: # 5000step마다 출력
    print(loss)
  optimize(learning_rate) # w,b파라미터 조정
####This section is not operating####

In [ ]:
import torch
'''Tensor
Scalar: 0dim tensor
Vector: 1dim Tensor
Matrix: 2dim Tensor
Image : 3dim Tensor
-> usually use 5dims in deep learning
'''

# 0dim Tensor
x=torch.tensor(10)
print("0 dim Tensor",x)
print("Dimension: ",x.dim())

# 1dim Tensor :Vector
# -> Float, Long type tensor
x=torch.rand(10) # 10개의 0부터1을 뽑음
print(x)
print("Dimension: ",x.dim())

temp = torch.FloatTensor([23,24,24.5,26,27,27,23.3]) 
print("Tensor size: ", temp.size())

# 2 dim Tenro : Matrix
z=torch.rand([20,10])
print("z tensor size:", z.size())
print(z[:2])

# 3 dim Tensor: Image
"""
3차원은 표기하기 힘드므로 예제
from PIL import Image
x= np.array(Image,open('panda.jpg').resize(224,224))
x_tensor=torch.from_numpy(x) # torch의 tensor로 np 변경
plt.imshow(x)
"""

0 dim Tensor tensor(10)
Dimension:  0
tensor([0.5907, 0.6854, 0.3301, 0.3051, 0.1083, 0.9758, 0.4530, 0.3957, 0.8323,
        0.2123])
Dimension:  1
Tensor size:  torch.Size([7])
z tensor size: torch.Size([20, 10])
tensor([[0.7937, 0.0803, 0.9679, 0.5490, 0.7160, 0.2541, 0.6349, 0.7771, 0.5299,
         0.3332],
        [0.8393, 0.7855, 0.9882, 0.8230, 0.5843, 0.1193, 0.8878, 0.0728, 0.8311,
         0.4179]])


In [ ]:
#Tensor slicing
#dict slicing 과 동일

sales = torch.eye(3,3) #대각행렬 만들고 대각요소를 1로 채움 
print(sales[1,1]) # 대각 행렬 검사

# 4차원 이상의 텐서는 이미지 연속처리에 보통 사용한다.
'''
cats=glob(data_path+'*.jpg')
cat_imgs=np.array([np.array(Image.open(cat).resize(224,224) for cat in cats[:64]])
cat_imgs
--> Tensor : 64*224*224*3 channel
64장의 이미지 동시 로딩 라고 볼 수 있음
'''

tensor(1.)

In [ ]:
#Calculation
a=torch.rand(2,2)
b=torch.rand(2,2)
c=a+b
d=torch.add(a,b)
a.add_(5)
a*b
a.mul(b)

In [ ]:

import torch

#cuda-> GPU Tensor

#cpu tensor 객체
a=torch.rand(10000,10000)
b=torch.rand(10000,10000)
a.matmul(b)

#gpu tensor 객체로의 변환
a=a.cuda()
b=b.cuda()
a.matmul(b)


In [ ]:
#Variiable 가변 계산 그래프 <- Tensor 객체, 기울기, Variable생성하는 함수의 참조로 구성
import torch
from torch.autograd import Variable
x=Variable(torch.ones(2,2),requires_grad=True)

y=x.mean()
y.backward() # 기울기 계산
print(x.grad)
print(x.grad_fn)
print(x.data)
print(y.grad_fn)

def get_data():#처음 값 받아오기
  train_X=np.asarray([3.3,4.4,5.5,6.71,6.93,4.168])
  train_Y=np.asarray([1.7,2.76,2.09,3.19,1.694,1.573])
  
  dtype=torch.FloatTensor
  X=Variable(torch.from_numpy(train_X)/type(dtype),requires_grad=False).view(17,1)
  y=Variable(torch.from_numpy(train_Y)/type(dtype),requires_grad=False)
  return X,y

def get_weights(): #가중치 및 bias를 random하게 불러오기
  w=Variable(torch.randn(1),requires_grad=True)
  b=Variable(torch.randn(1),requires_grad=True)
  return w,b

# Network 구현
def simple_network(x): #-> nn.Linear(17,1)
  y_pred=torch.matmul(x,w)+b #xW+b
  return y_pred

# 손실함수 loss function
def loss_fn(y,y_pred):
  loss=(y_pred-y).pow(2).sum() # ^2 +^2
  for param in [w,b]: # 각 가중치와 바이어스에 대해
    if not param.grad is None: # gradient 값이 존재하면 
      param.grad.data.zero_() #모두 0으로 만들어주고
  loss.backward() # backward propagation을 통해 gradient와 나머지 계산
  return loss.data[0]

def optimize(learning_rate): # optimizing 
  w.data-=learning_rate*w.grad.data
  b.data-=learning_rate*b.grad.data

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
None
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Data setting
from torch.utils.data import Dataset

class DogsAndCatsDataset(Dataset):
  def __init__(self,): #초기화
    pass
  def __len__(self): # 최대 요소수 반환
    pass
  def __getitem__(self,idx): # 데이터셋에서 idx번째 해당요소 반환
    pass

class DogsAndCatsDataset(Dataset):
  def __init__(self,root_dir,size(224,224)):
    self.files=glob(root_dir)
    self.size=size
  def __len__(self):
    return len(self.files)
  def __getitem__self(idx):
    img=np.asarray(Image.open(self.files[idx])).resize(self.size))
    label=self.files[idx].split('/')[-2]
    return img,label

# CPU에게 권장되는 인스턴스 단위 : 1
# for image,label in dogsdset:
# GPU에게 권장되는 인스턴스 단위 : Batch size

# Data loading -> DataLoader
from torch.utils.data import DataLoader
dataloader=DataLoader(dogsdset,batch_size=32,num_workers=2)
for imgs,labels in dataloader:
  pass



In [ ]:
#Activation Function

#1.Sigmoid
